version: '2'

services:
  spark:
    container_name: spark
    image: bde2020/spark-master
    ports: 
      - 9180:8080
      - 9177:7077
      - 9181:8081
    links: 
      - elassandra
    volumes:
      # - /home/ubuntu/Docker/cassandra/mostafa-hosein:/var/lib/docker/volumes/data/python
      - /home/mostafa/Desktop/kafka-test/together/cassandra/mostafa-hosein:/var/lib/docker/volumes/data/python

  elassandra:
    image: strapdata/elassandra
    container_name: elassandra
    build: /home/mostafa/Desktop/kafka-test/together/cassandra
    # build:  /home/ubuntu/Docker/cassandra
    env_file:
    # - /home/ubuntu/Docker/cassandra
      - /home/mostafa/Desktop/kafka-test/together/cassandra/conf/cassandra.env
    volumes:
      # - /home/ubuntu/Docker/cassandra/jarfile:/var/lib/docker/volumes/data/_data
      - /home/mostafa/Desktop/kafka-test/together/cassandra/jarfile:/var/lib/docker/volumes/data/_data
    ports:
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
      - 9142:9142
      - 9160:9160
      - 9200:9200
      - 9300:9300

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - 2181:2181
  
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    links:
     - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on: 
      - elassandra

  # kafka_connect-cassandra:
  #   image: datamountaineer/kafka-connect-cassandra
  #   container_name: kafka-connect-cassandra
  #   ports:
  #     - 8083:8083
  #     - 9102:9102
  #   volumes: 
  #     -  /home/mostafa/Desktop/kafka-test/together/Kafka-Spark-Cassandra/kafka-connect-cassandra-1.2.1-2.1.0-all.jar:/jarfiles
  #   environment:
  #     - JAVA_OPTS=""
      # - connect.cassandra.contact.points=localhost
      # - KAFKA_ZOOKEEPER_CONNECT =  "zookeeper:2181"
      # - KAFKA_ADVERTISED_LISTENERS= "kafka:9092"
      # - connect.cassandra.port=9042
      # - connector.class=com.datamountaineer.streamreactor.connect.cassandra.sink.CassandraSinkConnector
      # - tasks.max=1
    # depends_on:
    #   - kafka
    #   - elassandra




  # prometheus:
  #   image: prom/prometheus
  #   container_name: prometheus
  #   ports:
  #     - 9090:9090
  #   volumes:  
  #     - ./mount/prometheus:/etc/prometheus
  #     - ./alertmanager/alert.rules:/alertmanager/alert.rules
  #   links:
  #     - kafka
  
  # alertmanager:
  #   image: prom/alertmanager
  #   container_name: alertmanager
  #   ports:
  #     - "9093:9093"
  #   volumes:
  #     - alertmanager:/alertmanager
